### ISSUE TITLE
CNAME vs ALIAS

### ISSUE THREAD

**Issue by jhmartin** [ringods/terraform-website-s3-cloudfront-route53#13]
Is there any case you're aware of where you'd prefer a Route53 CNAME over A-ALIAS? ALIAS records save the client from additional DNS lookups

**Comment by ringods** [comment]
@jhmartin you are right about the ALIAS records. Although the comments in the [r53-cname](https://github.com/ringods/terraform-website-s3-cloudfront-route53/blob/master/r53-cname/main.tf#L1-L3) module refer to a CloudFront distribution, you can let it point to a hosting somewhere else, e.g. Netlify, while your DNS is on Route53.
