### ISSUE TITLE
site-redirect module error

### ISSUE THREAD

**Issue by shavo007** [ringods/terraform-website-s3-cloudfront-route53#14]
Hi,

Just ran through the modules and got an error running the module above

"target field is needed"

But the readme doesnt outline this.

Example:

```
module "site-redirect" {
   source = "github.com/ringods/terraform-website-s3-cloudfront-route53//site-redirect"

   region = "${var.region}"
   domain = "www.xxx.com"
   duplicate-content-penalty-secret = "some-secret-password"
   deployer = "xxx"
   acm-certificate-arn = "arn:aws:acm:us-east-1:118195946080:certificate/0a124b1d-6988-4d46-8f50-c7a8a567a0f9"
   target = "${var.domain}"
}
```
Also, Im using an aws profile.

When i run the modules i have to run as

`AWS_PROFILE=xxx terraform plan`

does your modules support profile from aws provider?

```
provider "aws" {
  region     = "${var.region}"
  profile   = "thsmiko"
}
```

Awesome modules btw! ;-)

**Comment by MattiasGees** [comment]
@shavo007 AWS profiles don't have an impact on Terraform modules and will work out of the box.
I will take a look at the target this evening and provide you with an answer about that.

**Comment by shavo007** [comment]
target has been added in to a previous PR (#5 ) now
