### ISSUE TITLE
Question on site-redirect

### ISSUE THREAD

**Issue by shavo007** [ringods/terraform-website-s3-cloudfront-route53#15]
If my main site is https://example.com and redirecting the www version to the naked domain; do i need two security certificates?

I only have one currently which is for main site.
Example: example.com

In site redirect module i reused the same certificate.

So when I redirect from www.example.com browser reports certificate issue.

Thanks,
Shane.

**Comment by ringods** [comment]
If you are using the AWS Certificate Manager (ACM), you can use a single certificate if you generate it for `example.com` and add `*.example.com` as an additional name. See the screenshot below:

<img width="1312" alt="acmcertificate" src="https://user-images.githubusercontent.com/77923/36062281-565773e6-0e69-11e8-9af6-77026bbfc77d.png">

In your case, create a new ACM certificate with both names, update your naked domain and the redirect site with the new certificate. After that, you can remove the certificate only containing `example.com`.

**Comment by shavo007** [comment]
awesome @ringods  thats exactly what i needed to do. thanks for update
