### ISSUE TITLE
Cloudfront not set to use http2

### ISSUE THREAD

**Issue by shavo007** [ringods/terraform-website-s3-cloudfront-route53#16]
Hi,

I just ran chrome lighthouse test and I noticed http2 is not enabled:
https://developers.google.com/web/tools/lighthouse/audits/http2

Should that be variable defined in the module?

Thanks,
Shane.

**Comment by ringods** [comment]
Hello @shavo007, a pull request adding this option to the sources and with updated documentation would be very welcome.

**Comment by shavo007** [comment]
done @ringods  #17

**Comment by MattiasGees** [comment]
This is merged to master and released https://github.com/ringods/terraform-website-s3-cloudfront-route53/releases/tag/3.0.4
