### ISSUE TITLE
Make CloudFront price_class attribute configurable

### ISSUE THREAD

**Issue by mojeto** [ringods/terraform-website-s3-cloudfront-route53#18]
Hi,
I have a feature request

## What:
Expose CloudFront `price_class` attribute as an optional module variable.

## Why
So I can define where on the world a website is fast accessible. 

Let me know if you like this feature. 
I'm willing to create a PR.

Cheers and thank you for a great module.

**Comment by MattiasGees** [comment]
@mojeto sounds great. We will have no problem accepting this kind of feature.

**Comment by MattiasGees** [comment]
Released in https://github.com/ringods/terraform-website-s3-cloudfront-route53/releases/tag/3.0.5 and solved with https://github.com/ringods/terraform-website-s3-cloudfront-route53/pull/19
