### ISSUE TITLE
Publish the modules to registry.terraform.io?

### ISSUE THREAD

**Issue by ringods** [ringods/terraform-website-s3-cloudfront-route53#20]
The Terraform modules in this repo are frequently used. Should we publish these modules to the [Terraform Registry](https://registry.terraform.io/)?

**Comment by MattiasGees** [comment]
I don't think it is a bad idea. Are you also planning on moving this terraform module to https://github.com/terra-farm?

**Comment by ringods** [comment]
@MattiasGees my needs for the modules are covered. 

Since most of the updates will probably come from Skyscrapers customers, I might do this and add some Sky maintainers on the project so they can perform updates and publish to the registry. Can you discuss this with them?

**Comment by iuriaranda** [comment]
Closing this for now. We are planning on publishing our modules to the Terraform registry in the near future, but some structure changes need to be done for that. And we'll tackle it as a global effort for all our modules, so there's no need to have this issue open anymore.
