### ISSUE TITLE
Multiple profiles

### ISSUE THREAD

**Issue by amanbolat** [ringods/terraform-website-s3-cloudfront-route53#21]
I have 2 aws profiles: `prod` and `dev`. Default is dev. 
Even if i set profile in provider like that:
```
provider "aws" {
  region = "ap-northeast-2"
  profile = "prod"
}
```
i don't know why, but it creates cloudfront distribution on my `prod` profile, but other resources will be deployed on my default profile.

I added `profile` variable and now it works correctly!

**Comment by ringods** [comment]
@amanbolat can you test with [v4.0.0](https://github.com/ringods/terraform-website-s3-cloudfront-route53/releases/tag/4.0.0) where the whole provider block is removed from the module?

**Comment by amanbolat** [comment]
@ringods I found that i should set aws profile ENV var before running `terraform apply`. Issue can be closed
