### ISSUE TITLE
remove hard coded tags

### ISSUE THREAD

**Issue by packeteer** [ringods/terraform-website-s3-cloudfront-route53#28]
The following tags are hard coded (in variables.tf):
tags.Project
tags.Environment
tags.Name

It would be good to remove the hard coding so that we can have a clean set of custom values.

**Comment by iuriaranda** [comment]
Hi @packeteer ,

Can you clarify? As far as I know the `tags` variable in `variables.tf` is empty by default and the user is free to set whatever set of tags he wants in there.

**Comment by packeteer** [comment]
if the user does not set their own values for these tags, then they end up with the following:
Project:noproject
Environment:default
Name:noproject-default-<hostname>

**Comment by iuriaranda** [comment]
@packeteer I've created a PR to clean up / remove those variables from the module. Do you think that fits your use-case?

https://github.com/skyscrapers/terraform-website-s3-cloudfront-route53/pull/36

**Comment by iuriaranda** [comment]
I've gone ahead and merged the PR and closed this issue. Feel free to re-open it or open a new one if you feel your initial issue has not been fully resolved.
