### ISSUE TITLE
Ability to define list of domain aliases (especially for wildcard subdomain handling)

### ISSUE THREAD

**Issue by olivermack** [ringods/terraform-website-s3-cloudfront-route53#29]
Hi,

currently it's not possible to utilize the functionality of multiple CNAMEs for the cloudfront distribution. In my case I'm trying to register a wildcard subdomain.

Due to the missing type in the variable declaration we're not able to pass a list, although the terraform resource allows a list: https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#aliases

In addition to that: if we just provide a wildcard-domain, e.g. `*.test.example.com`, the default tag handling creates invalid tags (asterisks are not allowed as it seems).

Best

**Comment by iuriaranda** [comment]
Hi @olivermack, thanks for your input.
Would you be willing to submit a PR with the changes you propose?

**Comment by iuriaranda** [comment]
Closing this for now as it has become stale. Feel free to reopen it if you consider it necessary.
