### ISSUE TITLE
duplicate IAM policies

### ISSUE THREAD

**Issue by thraxil** [ringods/terraform-website-s3-cloudfront-route53#3]
Both `site-main` and `site-redirect` try to create an `aws_iam_policy` resource with the name `"site.${replace("${var.domain}",".","-")}.deployer"`. Since the `domain` variable will generally be the same for the main and redirect buckets, the result is an error from Terraform/AWS like:

```
* aws_iam_policy.site_deployer_policy: Error creating IAM policy site.my-domain-com.deployer: EntityAlreadyExists: A policy called site.my-domain-com.deployer already exists. Duplicate names are not allowed.
        status code: 409, request id: 38816639-7dd1-11e6-9f1a-6d0a94ff2f5f
```

Seems like adding a `-main` and `-redirect` or something to the policy name would be an easy enough fix.  Alternatively, since the `deployer_role_policy.json` file that they each use is identical, perhaps just a refactor so it only tries to create it once?

**Comment by ringods** [comment]
@thraxil,

Regarding your quote:

> Since the domain variable will generally be the same for the main and redirect buckets

Why should I want to create a redirect site with the same domain name as the main site? The intent is that I can e.g. redirect from `www.domain.com` to `domain.com`, vice-versa or even between two totally different domains. As a result, the `domain` variable you are referring to is different for the creation of each of the policies.

Can you elaborate how you want to use the modules?

(and sorry for the late reply)

**Comment by iuriaranda** [comment]
Closing this for now as it has become stale, feel free to reopen it if necessary.
