### ISSUE TITLE
Make "deployer" optional

### ISSUE THREAD

**Issue by arjitj2** [ringods/terraform-website-s3-cloudfront-route53#43]
Happy to make the PR myself, but wondering if you'd agree to "deployer" being optional for site-main?

Some of us already have managed IAM roles with superuser access, or some of us (bad i know) just use the root user on our own AWS accounts.

So, for these cases we don't need this IAM Role Policy Attachment.

**Comment by iuriaranda** [comment]
Hi @arjitj2 , thanks for your contribution. I understand the need for this. We ourselves mainly use IAM roles, and have followed slightly different approaches on other modules.

I've added a small comment in your PR though.

**Comment by iuriaranda** [comment]
I'm going to close this issue as your PR is merged. Feel free to reopen it or open a new one if you need it.
